"""Generate copy-paste image prompts for new cooking pantry foods."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "seeds" / "FOODS_COOKING_IMAGE_PROMPTS.md"

BOILER = """Create a professional realistic product photo of Vietnamese food item "{name_en}". Professional realistic food product photography for a nutrition/fitness website. Format: WebP or JPEG, 1920x1080 pixels, 16:9 aspect ratio. Pure clean solid white background, minimal studio setup. Soft even natural studio lighting, sharp focus, true-to-life colors and textures. No people, no human hands, no plates, bowls, knives, cutting boards, or props. No text, labels, logos, watermarks, or nutrition info. Single unified composition (NOT a split-panel, NOT a collage, NOT two separate frames). Show TWO states of the SAME food standing very close together side by side in one shot, almost touching, visually similar size and scale, balanced and easy to recognize. CRITICAL depth order: Part 2 (prepared/edible state) must stand in the FRONT / foreground; Part 1 (original/whole state) must stand slightly BEHIND Part 2. Subject group centered, overall food content fills about 80% of the frame. Consistent catalog style across the food dataset — prioritize realism, clarity, and recognizability over artistic effects. FRONT (Part 2 – prepared, must be in front): {front} BACK (Part 1 – original, slightly behind): {back} The two food objects must stand closely next to each other in one continuous scene, with Part 2 clearly closer to the camera than Part 1. Use the most suitable 3/4 (or best clarifying) camera angle so shape and structure are obvious. Photorealistic commercial catalog look suitable for a fitness/nutrition website food database."""

# slug, name_vi, name_en, short_tag, front, back
ITEMS: list[tuple[str, str, str, str, str, str]] = [
    (
        "nuoc-mam",
        "Nước mắm",
        "Nước mắm (Vietnamese fish sauce)",
        "Gia vị Việt",
        "a compact glossy oval of amber-gold Vietnamese fish sauce sitting directly on the white surface, showing true reddish-brown translucency, viscosity, and tiny natural sediment, no container.",
        "a plain unlabeled clear glass bottle filled with the same amber fish sauce, natural 3/4 angle, no cap text, no brand.",
    ),
    (
        "nuoc-tuong",
        "Nước tương",
        "Nước tương (soy sauce)",
        "Gia vị Việt",
        "a compact glossy oval of dark brown soy sauce sitting directly on white, showing deep mahogany color, sheen, and slight thickness, no container.",
        "a plain unlabeled clear glass bottle filled with the same dark soy sauce, 3/4 angle, no brand.",
    ),
    (
        "mam-tom",
        "Mắm tôm",
        "Mắm tôm (fermented shrimp paste)",
        "Mắm Việt",
        "a small dense smear-mound of pink-gray Vietnamese shrimp paste showing grainy fermented texture, moist surface, and characteristic pungent-looking paste body, no dish.",
        "a compact unspread lump of the same shrimp paste, whole uncut mass, natural irregular shape, 3/4 angle.",
    ),
    (
        "mam-ruoc",
        "Mắm ruốc",
        "Mắm ruốc (Hue fermented krill paste)",
        "Mắm Huế",
        "a small dense smear-mound of purple-brown Hue mắm ruốc showing fine krill grain, oily sheen, and fermented paste texture, no dish.",
        "a compact unspread lump of the same mắm ruốc, whole mass, 3/4 angle.",
    ),
    (
        "dau-an",
        "Dầu ăn",
        "Dầu ăn (cooking oil)",
        "Dầu nấu",
        "a compact glossy oval of pale golden vegetable cooking oil sitting directly on white, showing transparency, viscosity, and light refraction, no container.",
        "a plain unlabeled clear glass bottle filled with the same pale golden cooking oil, 3/4 angle, no brand.",
    ),
    (
        "duong-cat",
        "Đường cát trắng",
        "Đường cát trắng (white granulated sugar)",
        "Gia vị ngọt",
        "a small neat mound of white granulated sugar with a cut/open face so individual crystal facets are clearly visible, no bowl.",
        "a slightly larger intact heap of the same white sugar, uncut pile, natural granulated texture, 3/4 angle.",
    ),
    (
        "muoi",
        "Muối",
        "Muối (table salt)",
        "Gia vị mặn",
        "a small neat mound of white salt with a cut/open face showing fine crystals, no bowl.",
        "a slightly larger intact heap of the same white salt, uncut pile, 3/4 angle.",
    ),
    (
        "tieu-den",
        "Tiêu đen",
        "Tiêu đen (black pepper)",
        "Gia vị cay",
        "a small mound of coarsely cracked / freshly ground black pepper showing gray-brown powder and broken peppercorn pieces, no bowl.",
        "a compact cluster of whole intact black peppercorns, uncrushed, wrinkled peppercorn skins clearly visible, 3/4 angle.",
    ),
    (
        "ot-hiem",
        "Ớt hiểm",
        "Ớt hiểm (bird's eye chili)",
        "Ớt Việt",
        "the same small Vietnamese bird's eye chili cut lengthwise to clearly show seeds, pale pith, and red flesh interior.",
        "whole intact fresh red ớt hiểm, uncut, glossy skin, natural pointed chili shape, 3/4 angle. Include 2–3 whole chilies clustered with the cut one, same scale.",
    ),
    (
        "giam-gao",
        "Giấm gạo",
        "Giấm gạo (rice vinegar)",
        "Gia vị chua",
        "a compact glossy oval of pale straw-colored rice vinegar sitting directly on white, showing watery clarity and faint golden tint, no container.",
        "a plain unlabeled clear glass bottle filled with the same pale rice vinegar, 3/4 angle, no brand.",
    ),
    (
        "toi",
        "Tỏi",
        "Tỏi (garlic)",
        "Củ gia vị",
        "several peeled garlic cloves plus one clove cut in half to clearly show creamy interior and clove structure.",
        "one whole intact fresh garlic bulb with papery white-purple skin, uncut, natural bulb shape, 3/4 angle.",
    ),
    (
        "hanh-tim",
        "Hành tím khô",
        "Hành tím khô (shallot)",
        "Củ gia vị",
        "one peeled shallot cut in half to clearly show concentric purple-white rings and moist interior.",
        "whole intact dry Vietnamese shallots with copper-purple papery skin, uncut, pointed bulb shape, 3/4 angle.",
    ),
    (
        "sa",
        "Sả",
        "Sả (lemongrass)",
        "Cây gia vị",
        "one lemongrass stalk smashed and sliced at the pale bulb to clearly show concentric rings, fibrous interior, and green-to-white gradient.",
        "whole intact fresh lemongrass stalks, uncut, long slender shape with green tops and pale bulbs, 3/4 angle.",
    ),
    (
        "gung",
        "Gừng",
        "Gừng (ginger)",
        "Củ gia vị",
        "a thick cross-section of ginger cut to clearly show bright yellow fibrous flesh, juice beads, and ring structure.",
        "whole intact knobby fresh ginger rhizome with tan skin, uncut, natural irregular shape, 3/4 angle.",
    ),
    (
        "rieng",
        "Riềng",
        "Riềng (galangal)",
        "Củ gia vị",
        "a thick slice of galangal cut to clearly show pale cream striated flesh, dense fibers, and pinkish skin edge.",
        "whole intact fresh galangal rhizome, uncut, smoother and paler than ginger, natural shape, 3/4 angle.",
    ),
    (
        "nghe",
        "Nghệ tươi",
        "Nghệ tươi (fresh turmeric)",
        "Củ gia vị",
        "a thick cut of fresh turmeric showing vivid orange interior, staining juice, and ringed flesh.",
        "whole intact fresh turmeric rhizome with brown-orange skin, uncut, small knobby fingers, 3/4 angle.",
    ),
    (
        "la-lot",
        "Lá lốt",
        "Lá lốt (piper lolot leaf)",
        "Rau thơm",
        "two or three heart-shaped lolot leaves slightly overlapping in front, showing dark green shiny upper side, paler underside, and clear veins.",
        "a small loose bunch of whole intact fresh lá lốt, uncut stems attached, natural leaf stack, 3/4 angle.",
    ),
    (
        "la-chanh",
        "Lá chanh",
        "Lá chanh (kaffir lime leaf)",
        "Rau thơm",
        "one kaffir lime leaf turned to clearly show the distinctive double-leaf / hourglass shape, glossy dark green surface, and oil glands.",
        "a small sprig of whole intact fresh kaffir lime leaves on a short stem, uncut, 3/4 angle.",
    ),
    (
        "ngo-om",
        "Ngò om",
        "Ngò om (rice paddy herb)",
        "Rau thơm",
        "a few rice-paddy-herb stems in front showing tiny paired green leaves, slender stems, and delicate herb texture.",
        "a small bunch of whole intact fresh ngò om, uncut, natural herb cluster, 3/4 angle.",
    ),
    (
        "bac-ha-rau",
        "Bạc hà (rau canh chua)",
        "Bạc hà canh chua (taro stem / dọc mùng)",
        "Rau canh",
        "two taro stems (dọc mùng / bạc hà canh chua) cut to clearly show the hollow pale pink-green interior and spongy walls.",
        "whole intact fresh bạc hà stems with pale pink-green hollow stalks and a few leaves, uncut, 3/4 angle.",
    ),
    (
        "thi-la",
        "Thì là",
        "Thì là (dill)",
        "Rau thơm",
        "a few dill fronds spread in front showing feathery fine leaflets and bright green color.",
        "a small bunch of whole intact fresh dill, uncut, natural herb cluster, 3/4 angle.",
    ),
    (
        "kinh-gioi",
        "Kinh giới",
        "Kinh giới (Vietnamese balm)",
        "Rau thơm",
        "several Vietnamese-balm leaves in front showing serrated edges, textured surface, and mint-family shape.",
        "a small bunch of whole intact fresh kinh giới, uncut, 3/4 angle.",
    ),
    (
        "toi-tay",
        "Tỏi tây",
        "Tỏi tây (leek)",
        "Rau củ",
        "a thick leek cross-section cut to clearly show concentric white-and-green rings and layered structure.",
        "one whole intact fresh leek, uncut, white base fading to dark green leaves, 3/4 angle.",
    ),
    (
        "can-tay",
        "Cần tây",
        "Cần tây (celery)",
        "Rau củ",
        "celery stalks cut to clearly show the crescent cross-section, strings, and pale green hollow-ish interior.",
        "a whole intact fresh celery bunch with leafy tops, uncut, 3/4 angle.",
    ),
    (
        "chanh-ta",
        "Chanh ta",
        "Chanh ta (Vietnamese lime)",
        "Quả chua",
        "the same Vietnamese lime cut in half to clearly show juicy pale-green pulp, thin rind, and seeds.",
        "whole intact fresh chanh ta, uncut, small round green-yellow lime, natural fruit shape, 3/4 angle.",
    ),
    (
        "sau-xanh",
        "Sấu xanh",
        "Sấu xanh (dracontomelon)",
        "Quả chua",
        "one green sấu fruit cut to clearly show pale tart flesh, stone, and interior structure.",
        "whole intact fresh green sấu, uncut, small round slightly flattened fruit, 3/4 angle.",
    ),
    (
        "ngo-gai",
        "Ngò gai",
        "Ngò gai (culantro)",
        "Rau thơm",
        "one or two long culantro leaves in front showing sawtooth edges, prominent midrib, and glossy dark green surface.",
        "a small bunch of whole intact fresh ngò gai, uncut long leaves, 3/4 angle.",
    ),
    (
        "cua-dong",
        "Cua đồng",
        "Cua đồng (rice-field crab)",
        "Hải sản đồng",
        "one field crab opened/cleaned to clearly show orange roe, white body meat, and interior structure, no plate.",
        "whole intact fresh Vietnamese rice-field crabs, uncut, dark green-brown shells, claws tucked, 3/4 angle.",
    ),
    (
        "hen",
        "Hến",
        "Hến (baby clam)",
        "Hải sản đồng",
        "several baby clams opened to clearly show the small orange-tan meats inside the shells, no plate.",
        "a compact cluster of whole intact closed hến with dark shells, unopened, 3/4 angle.",
    ),
    (
        "luon",
        "Lươn đồng",
        "Lươn đồng (swamp eel)",
        "Cá đồng",
        "a cleaned section of swamp eel cut to clearly show white-pink flesh, bone, and skin edge, no plate.",
        "one whole intact fresh swamp eel, uncut, long dark cylindrical body, natural curve, 3/4 angle.",
    ),
    (
        "ca-linh",
        "Cá linh",
        "Cá linh (Mekong linh fish)",
        "Cá đồng",
        "one small linh fish cut/gutted to clearly show silvery skin, pale flesh, and interior, no plate.",
        "a compact cluster of whole intact fresh cá linh, small slender silver freshwater fish, uncut, 3/4 angle.",
    ),
    (
        "thit-trau",
        "Thịt trâu",
        "Thịt trâu (buffalo meat)",
        "Thịt đỏ",
        "thick slices of raw buffalo meat in front showing deep red grain, lean muscle fibers, and a little fat.",
        "one whole intact raw buffalo steak/chunk, uncut, natural meat block, 3/4 angle.",
    ),
    (
        "chan-gio-heo",
        "Chân giò heo",
        "Chân giò heo (pork hock)",
        "Thịt heo",
        "a pork hock cut across to clearly show skin, white fat, pink meat, and round bone in the center.",
        "one whole intact raw pork hock, uncut, skin-on, natural joint shape, 3/4 angle.",
    ),
    (
        "xuong-ong-bo",
        "Xương ống bò",
        "Xương ống bò (beef marrow bone)",
        "Xương bò",
        "one beef marrow bone cut to clearly show rich creamy marrow inside the round bone, no plate.",
        "whole intact raw beef marrow bones, uncut long bones with meat traces, 3/4 angle.",
    ),
    (
        "canh-ga",
        "Cánh gà",
        "Cánh gà (chicken wing)",
        "Gia cầm",
        "one raw chicken wing joint cut or separated to clearly show skin, meat, and bone structure.",
        "whole intact raw chicken wings, uncut, skin-on, natural wing shape, 3/4 angle.",
    ),
    (
        "long-heo",
        "Lòng heo",
        "Lòng heo (pork offal mix)",
        "Nội tạng",
        "a cleaned prepared piece of pork intestine/stomach in front showing pale cooked-ready texture and coiled structure, appetizing catalog look, no plate.",
        "whole intact raw mixed pork offal pieces (intestine coils), uncut, natural pale color, 3/4 angle. Keep the look clean and catalog-like, not gory.",
    ),
    (
        "gan-heo",
        "Gan heo",
        "Gan heo (pork liver)",
        "Nội tạng",
        "a thick slice of raw pork liver showing fine maroon grain, moist cut face, and interior structure.",
        "one whole intact raw pork liver lobe, uncut, smooth dark reddish-brown surface, 3/4 angle.",
    ),
    (
        "gau-bo",
        "Gầu bò",
        "Gầu bò (beef brisket fat cap)",
        "Thịt bò",
        "slices of raw gầu bò showing distinct layers of beef meat and white fat cap.",
        "one whole intact raw piece of beef brisket fat-cap, uncut, 3/4 angle.",
    ),
    (
        "gio-bo",
        "Gìn bò / giò bò",
        "Giò bò (beef shank tendon)",
        "Thịt bò",
        "a slice of beef shank/tendon showing translucent tendon, lean meat, and connective tissue.",
        "one whole intact raw beef shank tendon piece, uncut, 3/4 angle.",
    ),
    (
        "bi-heo",
        "Bì heo",
        "Bì heo (shredded pork skin)",
        "Thịt heo",
        "a small nest of finely shredded cooked pork skin (bì) showing thin white-ivory strands, no plate.",
        "a compact sheet/block of cooked pork skin before shredding, intact, 3/4 angle.",
    ),
    (
        "cha-trung",
        "Chả trứng hấp",
        "Chả trứng hấp (steamed egg meatloaf)",
        "Chả Việt",
        "a thick slice of steamed egg meatloaf showing yellow egg interior mixed with minced pork, smooth steamed texture.",
        "one whole intact steamed chả trứng loaf, uncut, golden-brown steamed surface, 3/4 angle.",
    ),
    (
        "pate-gan",
        "Pate gan",
        "Pate gan (liver pâté)",
        "Pate Việt",
        "a thick slice of Vietnamese liver pâté showing creamy pink-brown interior, fine smooth paste, no knife.",
        "one whole intact pâté log/block, uncut, natural loaf shape, 3/4 angle.",
    ),
    (
        "cha-lua",
        "Chả lụa",
        "Chả lụa (Vietnamese pork roll)",
        "Giò chả",
        "two pale slices of chả lụa showing smooth bouncy white-pink interior and tiny pepper specks.",
        "one whole intact cylindrical pork roll, uncut, wrapped-look without branded text, 3/4 angle.",
    ),
    (
        "trung-muoi",
        "Trứng muối",
        "Trứng muối (salted duck egg)",
        "Trứng",
        "the same salted duck egg cut in half to clearly show oily orange-red yolk, firm white, and rich interior.",
        "whole intact salted duck egg in shell, uncut, dusty pale shell, 3/4 angle.",
    ),
    (
        "banh-mi",
        "Bánh mì",
        "Bánh mì (Vietnamese baguette)",
        "Bánh mì",
        "the same Vietnamese baguette cut to clearly show airy white crumb, thin crisp golden crust, and interior holes.",
        "one whole intact Vietnamese baguette, uncut, slender crispy loaf, 3/4 angle.",
    ),
    (
        "banh-trang",
        "Bánh tráng",
        "Bánh tráng (rice paper)",
        "Bánh khô",
        "one dry rice-paper sheet slightly curved/translucent in front so the round shape, rice dots, and thinness are obvious.",
        "a small stack of whole intact round bánh tráng sheets, uncut, 3/4 angle.",
    ),
    (
        "hu-tieu",
        "Hủ tiếu tươi",
        "Hủ tiếu tươi (fresh hu tieu noodles)",
        "Sợi tươi",
        "a loosened nest of fresh hu tieu noodles in front showing flat-thin rice strands and moist texture, no bowl.",
        "a compact tied/folded bundle of whole intact fresh hu tieu, uncut bundle, 3/4 angle.",
    ),
    (
        "bot-gao",
        "Bột gạo",
        "Bột gạo (rice flour)",
        "Bột",
        "a small mound of white rice flour with a cut/open face showing fine powder texture, no bowl.",
        "a slightly larger intact heap of the same rice flour, uncut pile, 3/4 angle.",
    ),
    (
        "bot-nang",
        "Bột năng",
        "Bột năng (tapioca starch)",
        "Bột",
        "a small mound of snow-white tapioca starch with a cut/open face showing ultra-fine silky powder, no bowl.",
        "a slightly larger intact heap of the same tapioca starch, uncut pile, 3/4 angle.",
    ),
    (
        "dau-xanh",
        "Đậu xanh cà vỏ",
        "Đậu xanh (mung bean)",
        "Đậu",
        "a small pile of split hulled yellow mung beans showing interior cotyledons, no bowl.",
        "a compact pile of whole intact dry green mung beans with skins, uncut, 3/4 angle.",
    ),
    (
        "dau-phong",
        "Đậu phộng rang",
        "Đậu phộng rang (roasted peanuts)",
        "Hạt",
        "a small pile of roasted shelled peanut kernels showing golden-brown skins and split interiors, no bowl.",
        "a compact cluster of whole intact unshelled peanuts, uncut, fibrous shells, 3/4 angle.",
    ),
    (
        "nuoc-dua-tuoi",
        "Nước dừa tươi",
        "Nước dừa tươi (fresh coconut water)",
        "Nước quả",
        "a compact glossy oval of clear slightly cloudy fresh coconut water sitting directly on white, showing transparency, no glass.",
        "one whole intact young green coconut, uncut, natural fruit shape, 3/4 angle.",
    ),
    (
        "banh-hoi",
        "Bánh hỏi",
        "Bánh hỏi (fine rice vermicelli sheet)",
        "Bún sợi",
        "a loosened square of bánh hỏi in front showing the woven ultra-fine white rice-vermicelli mesh, no plate.",
        "a folded intact stack of bánh hỏi sheets, uncut bundle, 3/4 angle.",
    ),
    (
        "banh-da",
        "Bánh đa đỏ",
        "Bánh đa đỏ (red rice noodles)",
        "Sợi đỏ",
        "loosened reddish-brown bánh đa strands in front showing flat wide noodles and toasted rice color, no bowl.",
        "a compact nest/bundle of whole intact dried bánh đa đỏ, uncut, 3/4 angle.",
    ),
    (
        "soi-banh-canh",
        "Sợi bánh canh",
        "Sợi bánh canh (thick tapioca-rice noodles)",
        "Sợi tươi",
        "a few thick round bánh canh noodles in front, one cut to show chewy opaque white cross-section, no bowl.",
        "a compact bundle of whole intact fresh thick bánh canh strands, uncut, 3/4 angle.",
    ),
    (
        "mi-quang",
        "Mì Quảng sợi",
        "Mì Quảng sợi (Quang noodles)",
        "Sợi vàng",
        "loosened wide flat turmeric-yellow mì Quảng strands in front showing the broad noodle shape and golden color, no bowl.",
        "a compact bundle of whole intact fresh mì Quảng noodles, uncut, 3/4 angle.",
    ),
]


def render_prompt(item: tuple[str, str, str, str, str, str]) -> str:
    _slug, _name_vi, name_en, _tag, front, back = item
    return BOILER.format(name_en=name_en, front=front, back=back)


def main() -> None:
    prompts = [render_prompt(item) for item in ITEMS]
    OUT.write_text("\n\n".join(prompts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(ITEMS)} prompts)")


if __name__ == "__main__":
    main()
