from fastapi import APIRouter

from app.api.v1.crud_factory import create_crud_router
from app.core.permissions import AccessPolicy
from app.models.entities import (
    AiGeneration,
    AiQaMessage,
    AuthSession,
    BodyPartLabel,
    CalculatorLog,
    ClientNote,
    EquipmentLabel,
    EquipmentProduct,
    Equipment,
    Exercise,
    ExerciseEquipmentSuggestion,
    ExerciseLocalization,
    Export,
    ExportTemplate,
    Food,
    FoodAlias,
    FoodCategory,
    KnowledgeArticle,
    KnowledgeSeries,
    MealPlan,
    MealPlanItem,
    MuscleLabel,
    MuscleGroup,
    PaymentTransaction,
    Program,
    ProgramDay,
    ProgramDayExercise,
    ProgramDayMeal,
    Subscription,
    SubscriptionPlan,
    TrainerAssignedPlan,
    TrainerClient,
    TrainerProfile,
    User,
    UserAiUsage,
    UserDailyPlan,
    UserDailyPlanDay,
    UserDailyPlanExercise,
    UserDailyPlanMeal,
    UserProfile,
    UserProgramEnrollment,
    UserWorkoutPlan,
    UserWorkoutPlanExercise,
    WorkoutScheduleFrame,
    WorkoutScheduleFrameDay,
    WorkoutSession,
    WorkoutSessionSet,
)
from app.repositories.base import ResourceConfig

PUBLIC = AccessPolicy.PUBLIC_READ.value
AUTH = AccessPolicy.AUTH_READ.value
OWNER = AccessPolicy.OWNER.value
TRAINER = AccessPolicy.TRAINER.value
ADMIN = AccessPolicy.ADMIN.value

RESOURCE_CONFIGS: list[ResourceConfig] = [
    # ── Catalog (public read, admin write) ──
    ResourceConfig("Exercise", Exercise, "exercises", "Catalog", PUBLIC, pk_fields=("id",),
                   filterable_fields=("muscle_group_id", "exercise_type", "difficulty", "movement_role", "movement_pattern", "venue", "is_active")),
    ResourceConfig("MuscleGroup", MuscleGroup, "muscle-groups", "Catalog", PUBLIC,
                   filterable_fields=("slug",)),
    ResourceConfig("Equipment", Equipment, "equipment", "Catalog", PUBLIC,
                   filterable_fields=("slug", "category", "is_active")),
    ResourceConfig("ExerciseLocalization", ExerciseLocalization, "exercise-localizations", "Catalog", PUBLIC),
    ResourceConfig("BodyPartLabel", BodyPartLabel, "body-part-labels", "Catalog", PUBLIC, pk_fields=("key",), read_only=True),
    ResourceConfig("EquipmentLabel", EquipmentLabel, "equipment-labels", "Catalog", PUBLIC, pk_fields=("key",), read_only=True),
    ResourceConfig("MuscleLabel", MuscleLabel, "muscle-labels", "Catalog", PUBLIC, pk_fields=("key",), read_only=True),
    ResourceConfig("FoodCategory", FoodCategory, "food-categories", "Catalog", PUBLIC),
    ResourceConfig("Food", Food, "foods", "Catalog", PUBLIC, filterable_fields=("category_id", "is_common", "food_kind", "status", "prep_state", "ai_eligible", "ai_priority", "region_slug", "province_id")),
    ResourceConfig("FoodAlias", FoodAlias, "food-aliases", "Catalog", PUBLIC),
    ResourceConfig("Program", Program, "programs", "Catalog", PUBLIC, filterable_fields=("goal", "level", "location")),
    ResourceConfig("ProgramDay", ProgramDay, "program-days", "Catalog", PUBLIC, filterable_fields=("program_id",)),
    ResourceConfig("ProgramDayExercise", ProgramDayExercise, "program-day-exercises", "Catalog", PUBLIC),
    ResourceConfig("ProgramDayMeal", ProgramDayMeal, "program-day-meals", "Catalog", PUBLIC),
    ResourceConfig(
        "WorkoutScheduleFrame",
        WorkoutScheduleFrame,
        "workout-schedule-frames",
        "Catalog",
        PUBLIC,
        read_only=True,
        filterable_fields=("experience_level", "sessions_per_week", "is_active"),
    ),
    ResourceConfig(
        "WorkoutScheduleFrameDay",
        WorkoutScheduleFrameDay,
        "workout-schedule-frame-days",
        "Catalog",
        PUBLIC,
        read_only=True,
        filterable_fields=("frame_id",),
    ),
    ResourceConfig("KnowledgeSeries", KnowledgeSeries, "knowledge-series", "Catalog", PUBLIC),
    ResourceConfig(
        "KnowledgeArticle",
        KnowledgeArticle,
        "knowledge-articles",
        "Catalog",
        PUBLIC,
        list_omit_fields=("content_md",),
    ),
    ResourceConfig("EquipmentProduct", EquipmentProduct, "equipment-products", "Catalog", PUBLIC),
    ResourceConfig(
        "ExerciseEquipmentSuggestion",
        ExerciseEquipmentSuggestion,
        "exercise-equipment-suggestions",
        "Catalog",
        PUBLIC,
        pk_fields=("exercise_id", "product_id"),
    ),
    ResourceConfig("ExportTemplate", ExportTemplate, "export-templates", "Catalog", PUBLIC, read_only=True),
    ResourceConfig("SubscriptionPlan", SubscriptionPlan, "subscription-plans", "Catalog", PUBLIC, read_only=True),
    # ── User-owned data ──
    ResourceConfig("UserProfile", UserProfile, "user-profiles", "Users", OWNER, owner_field="user_id"),
    ResourceConfig("UserProgramEnrollment", UserProgramEnrollment, "program-enrollments", "Users", OWNER, owner_field="user_id"),
    ResourceConfig("WorkoutSession", WorkoutSession, "workout-sessions", "Workouts", OWNER, owner_field="user_id"),
    ResourceConfig("WorkoutSessionSet", WorkoutSessionSet, "workout-session-sets", "Workouts", AUTH,
                   ownership_hops=(("session_id", WorkoutSession),)),
    ResourceConfig("MealPlan", MealPlan, "meal-plans", "Nutrition", OWNER, owner_field="user_id"),
    ResourceConfig("MealPlanItem", MealPlanItem, "meal-plan-items", "Nutrition", AUTH,
                   ownership_hops=(("meal_plan_id", MealPlan),)),
    ResourceConfig("CalculatorLog", CalculatorLog, "calculator-logs", "Tools", OWNER, owner_field="user_id"),
    ResourceConfig("UserWorkoutPlan", UserWorkoutPlan, "workout-plans", "Workouts", OWNER, owner_field="user_id"),
    ResourceConfig("UserWorkoutPlanExercise", UserWorkoutPlanExercise, "workout-plan-exercises", "Workouts", AUTH,
                   ownership_hops=(("plan_id", UserWorkoutPlan),)),
    ResourceConfig("UserDailyPlan", UserDailyPlan, "daily-plans", "Plans", OWNER, owner_field="user_id"),
    ResourceConfig("UserDailyPlanDay", UserDailyPlanDay, "daily-plan-days", "Plans", AUTH,
                   ownership_hops=(("plan_id", UserDailyPlan),)),
    ResourceConfig("UserDailyPlanExercise", UserDailyPlanExercise, "daily-plan-exercises", "Plans", AUTH,
                   ownership_hops=(("plan_day_id", UserDailyPlanDay), ("plan_id", UserDailyPlan))),
    ResourceConfig("UserDailyPlanMeal", UserDailyPlanMeal, "daily-plan-meals", "Plans", AUTH,
                   ownership_hops=(("plan_day_id", UserDailyPlanDay), ("plan_id", UserDailyPlan))),
    ResourceConfig("Export", Export, "exports", "Tools", OWNER, owner_field="user_id"),
    ResourceConfig("Subscription", Subscription, "subscriptions", "Billing", OWNER, owner_field="user_id"),
    ResourceConfig("AiGeneration", AiGeneration, "ai-generations", "AI", OWNER, owner_field="user_id"),
    ResourceConfig("AiQaMessage", AiQaMessage, "ai-qa-messages", "AI", OWNER, owner_field="user_id"),
    ResourceConfig("UserAiUsage", UserAiUsage, "ai-usage", "AI", OWNER, owner_field="user_id"),
    ResourceConfig("PaymentTransaction", PaymentTransaction, "payments", "Billing", OWNER, owner_field="user_id"),
    # ── Trainer module ──
    ResourceConfig("TrainerProfile", TrainerProfile, "trainer-profiles", "Trainer", TRAINER, owner_field="user_id"),
    ResourceConfig("TrainerClient", TrainerClient, "trainer-clients", "Trainer", TRAINER, owner_field="trainer_id"),
    ResourceConfig("ClientNote", ClientNote, "client-notes", "Trainer", TRAINER, owner_field="trainer_id"),
    ResourceConfig("TrainerAssignedPlan", TrainerAssignedPlan, "trainer-assigned-plans", "Trainer", TRAINER, owner_field="trainer_id"),
    # ── Admin-only ──
    ResourceConfig("User", User, "users", "Admin", ADMIN, read_only=True),
    ResourceConfig("AuthSession", AuthSession, "auth-sessions", "Admin", ADMIN, read_only=True),
]


def build_resource_routers() -> APIRouter:
    router = APIRouter()
    for config in RESOURCE_CONFIGS:
        router.include_router(create_crud_router(config))
    return router
